import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import SideNav from "@/src/components/organisms/SideNav";
import "./globals.css";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistMono.variable} antialiased`}
      >
        <div className="flex min-h-screen bg-background font-sans">
          <aside className="fixed left-0 top-0 h-screen w-52 border-r border-border bg-surface overflow-y-auto">
            <SideNav />
          </aside>
          <div className="flex-1 ml-52 min-h-screen overflow-y-auto">{children}</div>
        </div>
      </body>
    </html>
  );
}
